name: Elixir CI - AzarSa

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build_and_test:
    name: Compilación y Pruebas
    runs-on: ubuntu-latest
    
    steps:
    - name: Clean build
      run: mix clean

    - name: Descargar código
      uses: actions/checkout@v5 # Actualizado a v5 para soporte nativo de Node 24

    - name: Configurar Elixir y Erlang
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.19.0' # Versión de mix.exs
        otp-version: '26.0'

    - name: Instalar Dependencias
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Ejecutar Tests de Calidad
      run: mix test