name: Elixir CI - AzarSa

# ¿Cuándo se ejecuta? 
on:
  push:
    branches: [ "main", "develop" ] # Se dispara al subir cambios a estas ramas
  pull_request:
    branches: [ "main", "develop" ] # Se dispara al proponer cambios

jobs:
  build_and_test:
    name: Compilación y Pruebas
    runs-on: ubuntu-latest # Usamos un servidor Linux limpio en la nube

    steps:
    - name: Descargar código
      uses: actions/checkout@v4 # "Clona" el repo en el servidor de GitHub

    - name: Configurar Elixir y Erlang
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.19.0' # Versión definida en mix.exs
        otp-version: '26.0'

    - name: Instalar Dependencias
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get # Instala Jason y lo necesario

    - name: Ejecutar Tests de Calidad
      run: mix test # Ejecuta las pruebas actuales
